### PR TITLE
Handle security warning dialog

### PR DESCRIPTION
**Pull request by odockal**
Signed-off-by: Ondrej Dockal <odockal@redhat.com>

### CODE REVIEW

**Review by jeffmaury — CHANGES_REQUESTED** [review]
Please make sure package-lock.json is version 2 as Jan switched to that version
And still errored.
Shouldn'd the change be in extension-tester

**Comment by odockal** [comment]
@jeffmaury For the modal dialog, depends, but it will be handled by extester, so we can wait for new release. Also, the errors are caused by change in vscode. Again, we need to wait for extester to have patch and release. Or I can provide immediate fixes for everything (including updating package-lock version) and by setting a vscode version in ui tests that does not contain errors.

**Comment by jeffmaury** [comment]
We better wait for update (should be there today from @jrichter1) so that we align with other extensions

**Comment by odockal** [comment]
@jeffmaury I doubt there will be fix for change as well... (just my guess). But I update PR, so we can check in CI my assumption at least.

**Comment by odockal** [comment]
@jeffmaury So, latest working version is 1.55 which is something that must be used in UI tests to avoid errors. I think this is all I can do about it. Give it a shot or feel free to close in case you better wait for extester.

**Comment by jrichter1** [comment]
I just published 4.1.0, it should solve the problems you're experiencing. And if it doesn't... just let me know, I'll come up with something.

**Comment by jeffmaury** [comment]
Closing as update to extester fixed test errors

**Pull request closed without merging**
