### PR TITLE
Create Github Actions workflow file

### PR DESCRIPTION
**Pull request by odockal**
Introduce GitHub actions

### CODE REVIEW

**Comment by odockal** [comment]
@jeffmaury hello. I would suggest to switch to github actions instead of travis and appvoyer. But first it needs to be tested. wdyt?

**Comment by jeffmaury** [comment]
Not that urgent. I need the current prs to pass because I can't release

**Comment by odockal** [comment]
@jeffmaury no problem, fix for tests is in other pr.

**Comment by jeffmaury** [comment]
Your workflow has some issues so I tested and modified it on my fork (https://github.com/jeffmaury/vscode-project-initializer/tree/GA) but I still can't figure out why it's failing on Linux

**Comment by odockal** [comment]
@jeffmaury I can bet. It seems like the screen/app resolution is too small to provide full expected strings...

**Comment by odockal** [comment]
You might make use of manual xvfb set up for linux system https://github.com/juliangruber/browser-run/issues/147, restrict script for linux only, ie.:
```
 if: matrix.os == 'ubuntu-latest'
```

**Pull request closed without merging**
