### PR TITLE
Add license file EPL 2.0

### PR DESCRIPTION
**Pull request by odockal**
- add full test suite

Signed-off-by: Ondrej Dockal <odockal@redhat.com>

### CODE REVIEW

**Comment by odockal** [comment]
@jeffmaury Do you have any idea what's wrong with appveyor job?

**Comment by jeffmaury** [comment]
> 
> 
> @jeffmaury Do you have any idea what's wrong with appveyor job?

Looks like a mismatch between the old and new Github organization

**Comment by odockal** [comment]
@jeffmaury And what we can do you about it? Or who can?

**Comment by jeffmaury** [comment]
I tried to remove  AppVeyor app and webhooks from this repo and re enabled Appveyor then. We'll see with next PRs

**Comment by odockal** [comment]
@jeffmaury Perfect! Closing this Pr in favor of #51

**Pull request closed without merging**
